services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    platform: linux/amd64
    ports:
      - "1433:1433"
    volumes:
      - lutris:/home/app/db
      - ./api/src/sql:/tmp
      - ./api/seeder.sh:/tmp/seeder.sh
    environment:
      # TODO: change to use .env
      MSSQL_USER: docker
      MSSQL_PASSWORD: "yourStrong(!)Password"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: Y

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  lutris:
