version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - lutris:/home/app/db
      - ./api/seeder.sh:/docker-entrypoint-initdb.d/seeder.sh
      - ./seeds.sql:/tmp/seeds.sql
    entrypoint: /bin/bash -c "/docker-entrypoint-initdb.d/seeder.sh && /opt/mssql/bin/sqlservr"
    environment:
      # TODO: change to use .env
      MSSQL_USER: docker
      MSSQL_PASSWORD: password
      ACCEPT_EULA: Y

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  lutris:
